[package]
name = "codegen-luau"
version = "0.5.0"
edition = "2021"

[dependencies.wasm-ast]
path = "../../wasm-ast"

[dependencies.parity-wasm]
git = "https://github.com/paritytech/parity-wasm.git"
features = ["multi_value", "sign_ext"]

[[bin]]
name = "wasm2luau"
